# Example Sonatype Lift manifest scan

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: SonatypeLiftPipelineTask@1
  inputs:
    SonatypeLiftService: 'Sonatype Lift'
    stage: 'Build'
    scanTargets: '**/*'
    applicationDisplayName: '$(Build.Repository.Name)'
