# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: SonatypeLiftPipelineTask@1
  inputs:
    SonatypeLiftService: 'Sonatype Lift'
    stage: 'Build'
    scanTargets: '**/*'
    applicationDisplayName: '$(Build.Repository.Name)'
